### ISSUE TITLE
npm run hash error

### ISSUE THREAD

**Issue by BoChao-Hsu** [soruly/sola#10]
Hi,I run "npm run hash" , but run to "Compressing XML"  have a error 
`
Post-Processing XML
Compressing XML
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected close
    at succeed (/usr/sola/node_modules/amqplib/lib/connection.js:271:13)
    at onOpenOk (/usr/sola/node_modules/amqplib/lib/connection.js:253:5)
    at /usr/sola/node_modules/amqplib/lib/connection.js:166:32
    at /usr/sola/node_modules/amqplib/lib/connection.js:160:12
    at Socket.recv (/usr/sola/node_modules/amqplib/lib/connection.js:498:12)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitReadable_ (_stream_readable.js:534:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Connection.emit (events.js:182:13)
    at Connection.C.onSocketError (/usr/sola/node_modules/amqplib/lib/connection.js:352:10)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sola@0.3.0 hash: `node src/hash-video.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sola@0.3.0 hash script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-13T09_03_24_560Z-debug.log
`
/root/.npm/_logs/2018-11-13T09_03_24_560Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'hash' ]
2 info using npm@6.4.1
3 info using node@v10.12.0
4 verbose run-script [ 'prehash', 'hash', 'posthash' ]
5 info lifecycle sola@0.3.0~prehash: sola@0.3.0
6 info lifecycle sola@0.3.0~hash: sola@0.3.0
7 verbose lifecycle sola@0.3.0~hash: unsafe-perm in lifecycle true
8 verbose lifecycle sola@0.3.0~hash: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/sola/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle sola@0.3.0~hash: CWD: /usr/sola
10 silly lifecycle sola@0.3.0~hash: Args: [ '-c', 'node src/hash-video.js' ]
11 silly lifecycle sola@0.3.0~hash: Returned: code: 1  signal: null
12 info lifecycle sola@0.3.0~hash: Failed to exec hash script
13 verbose stack Error: sola@0.3.0 hash: `node src/hash-video.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid sola@0.3.0
15 verbose cwd /usr/sola
16 verbose Linux 4.18.16-300.fc29.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "hash"
18 verbose node v10.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error sola@0.3.0 hash: `node src/hash-video.js`
22 error Exit status 1
23 error Failed at the sola@0.3.0 hash script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

please help , thanks.

**Comment by BoChao-Hsu** [comment]
I think the error for this 
`If some tasks took too long to process (e.g. hashing long video with slow processor), you need to increase heartbeat interval on RabbitMQ. Found the line {heartbeat, 60}, in /etc/rabbitmq/rabbitmq.config and add {heartbeat, 1200} below it.`

/etc/rabbitmq/rabbitmq.config  <-- this file in rabbitmq docker ?

I need into `docker exec -it 'docker-id' /bin/bash 
inside modifiy this?

**Comment by soruly** [comment]
Oh right, you can try it that way for now.
I'll rebuild the docker image with that missing config.

**Comment by BoChao-Hsu** [comment]
but I can't chang this file , it's readOnly. 
And I try chmod 777 rabbitmq.config  not work.

**Comment by soruly** [comment]
I've updated the config `docker/rabbitmq/rabbitmq.config` in develop branch, you can git pull and `docker-compose up -d` again

**Comment by BoChao-Hsu** [comment]
thanks ~~  I'm happy because of you .
