### ISSUE TITLE
Can I change anime to movies？

### ISSUE THREAD

**Issue by c0py7hat** [soruly/sola#161]
Can I change anime to movies, and if I store GIFs or JPGs in it, can I recognize and request them? The required configuration is too high and I don't have that much money to download and process the video.

**Comment by soruly** [comment]
Yes. It is not restricted to anime. As long as your video is in mp4 format and is supported by ffmpeg, it can analyse the video. It will ignore anything that is not mp4, so gif and jpg would be skipped.
