### ISSUE TITLE
Can I run windows 10 or make a version for windows 10?

### ISSUE THREAD

**Issue by My12123** [soruly/sola#257]
Can I run windows 10 or make a version for windows 10?

**Comment by soruly** [comment]
It cannot run natively on Windows 10. But some users says it can be run using Windows Subsystem for Linux (WSL). However, instead of using sola (which is outdated), I'd recommend you to use docker compose from this repo.
https://github.com/soruly/trace.moe

**Comment by My12123** [comment]
![2022-12-24_10-09-35](https://user-images.githubusercontent.com/49092250/209425485-bad2103d-d150-459f-945c-128e2b52fffd.png)
How do I change the drive and path to the folder?

**Comment by My12123** [comment]
![2022-12-24_10-13-54](https://user-images.githubusercontent.com/49092250/209425591-5998a303-3744-4657-a2cc-f9e9276e21a1.png)

**Comment by My12123** [comment]
@soruly

**Comment by My12123** [comment]
@soruly ?

**Comment by soruly** [comment]
trace.moe is no longer based on this project anymore. Please use https://github.com/soruly/trace.moe instead
