### ISSUE TITLE
Search image not found.

### ISSUE THREAD

**Issue by BoChao-Hsu** [soruly/sola#6]
hi , i follow your tutorial to step 8 then crop one photo in video,use node src/search.js /tmp/1.jpg,result : [] ,why not found any video ? please help ,thanks.

**Comment by soruly** [comment]
check if your video hash is loaded into solr from the admin page (e.g. 127.0.0.1:8983)
you should see your some paths and numFound should be > 0
![image](https://user-images.githubusercontent.com/1979746/46253611-6c009380-c4b2-11e8-9306-ec36d13e5795.png)

**Comment by BoChao-Hsu** [comment]
uh.. numFound is 0 .
![q1](https://user-images.githubusercontent.com/34178564/46253729-a0c21a00-c4b5-11e8-9f29-aa6553a315bf.png)

but i run this  : npm run check-new 
swho↓
![q2](https://user-images.githubusercontent.com/34178564/46253747-eb439680-c4b5-11e8-8a39-58eaa6ec007f.png)
looks like success?

my database :
![q3](https://user-images.githubusercontent.com/34178564/46253762-6147fd80-c4b6-11e8-9e56-865fa411bf61.png)

how are video hash  insert solr ?

**Comment by soruly** [comment]
Now the files are hashed but not loaded into database yet
Start another worker with `npm run load`
The file status should be NEW --> HASHING --> HASHED --> LOADING --> LOADED

**Comment by BoChao-Hsu** [comment]
npm run load
![q4](https://user-images.githubusercontent.com/34178564/46254202-087c6300-c4be-11e8-8163-dc98b5a3f04b.png)

**Comment by BoChao-Hsu** [comment]
enum missing 'LOADING' ?
![q5](https://user-images.githubusercontent.com/34178564/46254286-88ef9380-c4bf-11e8-98b6-e4b3a158fa3c.png)

**Comment by BoChao-Hsu** [comment]
yes .. i alert table change status filed add 'LOADING' , fix this !

**Comment by soruly** [comment]
Oh my bad, give me a moment :man_facepalming:

**Comment by soruly** [comment]
I think this issue is resolved. If not, please reopen/open a new issue
